### ISSUE TITLE
add the file size limit for each site next to its name

### ISSUE THREAD

**Issue by Soundtoxin** [WeebDev/lolisafe#173]
Can you perhaps add the file upload limit for each site you list next to the name? I bothered to register on one just to find out it was smaller than I needed. criminals.host was only 100MB, and I have a 151MB file, so I probably need 200MB limit or more. Maybe this is outside the scope of this page. If so, sorry to bother you.

**Comment by RyoshiKayo** [comment]
I think it would be better just to have the upload max size displayed on the websites homepage. This project shouldn't be required to maintain an updated list with more than links to people's domains.

**Comment by RyoshiKayo** [comment]
It's actually there by default, so criminals.host either changed their home.html to remove the h3 tag with the `maxFileSize` ID.

**Comment by Pitu** [comment]
Adding a bit more information on the topic, not only it should be displayed regardless of being logged in or not but I'll be switching from readme to a dedicated file to keep track of lolisafe implementations so that the readme is only updated when pertinent. We can definitely add the max file size in there as well.
