### ISSUE TITLE
[FEATURE REQUEST] MIME-type blocking

### ISSUE THREAD

**Issue by Shumatsu** [WeebDev/lolisafe#192]
**Is your feature request related to a problem? Please describe.**
Not really a problem, just thought that this would be a better approach than only banning extensions.

**Describe the solution you'd like**
Blocking uploads of files that are of banned MIME-types (ex. application/x-dosexec, application/x-executable).

**Additional context**
Well, you can still upload executables without extensions. This is possibly a security flaw. MIME-type checking can be done client-side, and would thwart malicious usage at least to some degree.

**Comment by BobbyWibowo** [comment]
This is one of those things that I consider to be rather low priority.
Generally, people that actually fall for sketchy files downloaded from the internet would be using Windows (lul). And iirc Windows, at least its built-in File Explorer, use file extensions instead of mime types to detect their types.
So like, even if someone have downloaded a file with mime type `application/x-executable`, as long as the extension isn't `.exe` (or whatever other executable extensions), by default File Explorer won't simply just run the file like an executable.
I only know that Linux seem to rely a bit more deeply on mime types for file type detection.
There's also the fact that nginx will use file extensions to assign mime types for responses. So even if the actual file has `application/x-executable` mime type, if the extension is `.txt`, nginx will just tell client's browsers that the file's mime type is actually `text/plain` (or whatever you've configured in your nginx installation).
Though I guess I can see it being abused by naming an executable file with some obscure extension name that not many people know, but OS will somehow regard as yet another another executable (though if the extension isn't listen in nginx's mime type, the default behavior is to simply assign `application/octet-stream` and browsers will usually just save such files to disk by default instead of trying to execute it).
There's also the fact that archiving files is a pretty common solution to bypass extensions or mime types ban anyway.
So yeah, I guess it's pretty neat to have, but can't help but feel like it's a fruitless attempt.

**Comment by Pitu** [comment]
This is not something that will be implemented for the time being.
Most of the lolisafe clones are private since having an open one for the public is asking for trouble. So I'm not gonna put effort into further protecting oblivious users for sketchy mime types when we already have extension blocking.
