### ISSUE TITLE
Provided nginx config doesn't work with ssl?

### ISSUE THREAD

**Issue by ItsPaulM** [WeebDev/lolisafe#210]
I'm using the provided nginx config (i've tried both of them) however, my site doesn't respond to https - it just redirects to http. 

I'm using Cloudflare

**Comment by Pitu** [comment]
Then it's most likely a cloudflare issue. Use the https version of the nginx config and make sure your `SSL/TLS` config in Cloudflare is set to `Full (Strict)`

**Comment by Aareksio** [comment]
Answering possible followup problem - when using CF's option `Full (Strict)` make sure the certificate is signed by trusted CA. If you are using self signed certificate, select `Full` instead. 

Since there are ways of obtaining free SSL certificates from trusted CAs, I recommend getting one, refer to [LetsEncrypt](https://letsencrypt.org/) for instructions.

**Comment by ItsPaulM** [comment]
Thanks for the help guys! Managed to fix it with that first comment from Pitu. Thanks again :)
