### ISSUE TITLE
Uploading to lolisafe.moe issue

### ISSUE THREAD

**Issue by XCanG** [WeebDev/lolisafe#74]
Recently (1 day ago) I have no issues in my ShareX or with website, but today I was tried to upload image, but ShareX return empty responce error, so I go to website and login normally, uploads page seems ok and recent uploads are accessible. After I go on main page of website and try to upload I got an error `This account has been disabled`. So... does it mean what you planning to compleately close your website or... something actually with my account?
![default](https://user-images.githubusercontent.com/4011523/36346095-8281cad4-1459-11e8-86a3-927e1687bb63.png)

**Comment by Pitu** [comment]
Hi!
Yes, I made a change last night that revoked access to users since I'm making the official instance of lolisafe private. All your files are still there and will remain there but uploading is not gonna work anymore. The truth is that a bunch of people use lolisafe and paying for the bandwidth and storage of people's files is not something I was planning on doing, even though I did it for over a year.

In case you want to host a version of lolisafe yourself, you can download each album in .zip format to make the transition easier. 

I'm sorry it was confusing at first, and I'm sorry to have closed it without prior notice. I am looking into opening a new instance publicly though, so at least people have that to look forward to.

Again, sorry for the trouble 🙇

**Comment by XCanG** [comment]
Actually I just continue it using as solid working service. I like file limit size it have and having dashboard for deletion (expiring functionality will be also appreciated). Well I already prepared for that, so I have all my files on local drive.

How long actually site will up? I will think if I need to reupload some content to other place what frequently used over time.
