### ISSUE TITLE
Add Chunked file uploading

### ISSUE THREAD

**Issue by RyoshiKayo** [WeebDev/lolisafe#87]
Add chunked file uploading to get around CF Size limits and such.

Ref:
-http://www.componentix.com/blog/13/file-uploads-using-nodejs-once-again

#enhancement

**Comment by BobbyWibowo** [comment]
I got this working just a while ago (at least from what I can see when testing +300MB file chunked into 4 files, 100MB max). The codes are still rather dirty tho. Many repeats here and there.

My current mechanism is using Dropzone 5.2.0. They added chunked uploads support there.
Lolisafe is currently using 4.3.0 btw.

If they are chunked uploads, they will temporarily be stored at:
```
uploadDir/dzchunks/UUID/index.extension
```
for example:
```
uploadDir/dzchunks/123e4567-e89b-12d3-a456-426655440000/0.zip
uploadDir/dzchunks/123e4567-e89b-12d3-a456-426655440000/1.zip
...
uploadDir/dzchunks/123e4567-e89b-12d3-a456-426655440000/n.zip
```
then once all uploads are successfully finished, it will then POST the UUID (and original filename, file size and mime type for db) to a new API route `api/upload/finishchunks` so that it can finally combine then delete all the chunks and write the new file to db.

Oh, about the UUIDs, I think they're probably generated by Dropzone. It's always unique even when using the exact same file so I guess that works.

I had to add `rimraf` to the dependencies for deleting the temporary UUID dirs and the chunks in them btw (if someone have a native solution with fs-only or something, then please).

How do they all sound? I'll need a few days before I can do a PR though.

Missing (which I can't really be bothered to think about):
- Handling cases like user never sending a POST request to the finishchunks API even after some or all of the chunks have been uploaded.
- Tying the UUIDs to IP/token so that some random users can't send a POST request to the finishchunks API using those UUIDs, somehow.

**Comment by iCrawl** [comment]
@BobbyWibowo Sure man, just shoot the PR and I can go over it if you want

**Comment by BobbyWibowo** [comment]
been testing and perfecting this for a week. it's working well so far, but i'd like to wait for a proper eslint config or something before making a pr tailored for master :cry:

**Comment by Pitu** [comment]
This is already added and working on the next version releasing next week
